default: &default
  adapter: postgresql
  host: localhost
  port: 5432
  username: root
  password: root
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: tictactoe_development

test:
  <<: *default
  database: tictactoe_test

production:
  url: <%= ENV['DATABASE_URL'] %>
